server:
  port: 19091  # ????? ???? ??? ?? ??

spring:
  main:
    web-application-type: reactive  # Spring ??????? ???? ? ???????? ???
  application:
    name: gateway-service  # ?????? ??? 'gateway-service'? ??
  cloud:
    gateway:
      server:
        webflux:
          routes:  # Spring Cloud Gateway? ??? ??
            - id: order-service  # ??? ???
              uri: lb://order-service  # 'order-service'?? ???? ?? ???(lb://)? ???? ???
              predicates:
                - Path=/order/**  # /order/** ??? ???? ??? ? ???? ??
            - id: product-service  # ??? ???
              uri: lb://product-service  # 'product-service'?? ???? ?? ???(lb://)? ???? ???
              predicates:
                - Path=/product/**  # /product/** ??? ???? ??? ? ???? ??
          discovery:
            locator:
              enabled: true  # ??? ?????? ?? ???? ???? ????? ??

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/  # Eureka ??? URL? ??